all:
	gcc main.c framework/UIElements/Button.c framework/UIElements/Frame.c framework/UIElements/Label.c framework/UIElements/Utils.c framework/Sprite/sprite-main.c framework/Sprite/sprite-movements.c framework/Block/block-main.c -I../include/SDL2 -L../lib/SDL2 -lSDL2_ttf -lSDL2main -lSDL2 -o ../bin/wod
